# .github/actions/my-custom-action/action.yml
name: 'Varangian Guard - Fetch Tx'
description: 'Action to fetch the next Safe transaction that should be handled from the Safe transaction service'
author: 'rmeissner'

inputs:
  safe-address:
    description: "Address of the Safe to monitor (e.g. 0x0Da0...5afe)"
    required: true
  service-url:
    description: "Address of the Safe service"
    required: false
    default: "https://safe-transaction-gnosis-chain.safe.global/"
  safe-tx-hash:
    description: "Hash of a specific Safe transaction that should be fetched"
    required: false

outputs:
  safe-tx: # id of output
    description: 'Next transaction to execute'
    
runs:
  using: 'node20' # Specify the Node.js version to use
  main: 'dist/main.js' # Entry point for your action
      
