# .github/actions/my-custom-action/action.yml
name: 'Varangian Guard - Check'
description: 'Action to check and co-sign the specified Safe transaction'
author: 'rmeissner'

inputs:
  co-signer-material:
    description: "Private key material used for co-signing"
    required: true
  signature-1271-compatible:
    description: 'Flag to indicate if the signature should be 1271 compatible'
    required: false
    type: boolean
  safe-tx:
    description: "Safe Transaction to check"
    # required: true

outputs:
  co-signer-address:
    description: 'Address of the co-signer'
  co-signer-signature:
    description: 'Signature of the co-signer'

runs:
  using: 'node20' # Specify the Node.js version to use
  main: 'dist/main.js' # Entry point for your action