# .github/actions/my-custom-action/action.yml
name: 'Varangian Guard - Relay'
description: 'Action to relay a Safe transaction that has been approved'
author: 'rmeissner'

inputs:
  safe-tx:
    description: "Safe Transaction to relay"
    required: true
  co-signer-signature: # id of output
    description: 'Signature of the co-signer'

runs:
  using: 'node20' # Specify the Node.js version to use
  main: 'dist/main.js' # Entry point for your action